allow-lan: true
log-level: info
mode: Rule
port: 7890
proxies:
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: CNF-ALICE
  port: 23686
  reality-opts:
    public-key: 54-6ESzAXa7E7ZqCykrZ6IzmyqolcRRrneYr7cuNTyY
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: cnf.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
- client-fingerprint: chrome
  flow: null
  name: Alice
  port: 4441
  reality-opts:
    public-key: gMcIog-ZnwzfVGTio2Ua2BJffffi1wuzX97IQvoWVWk
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: alice.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: SG-CNF
  port: 4446
  reality-opts:
    public-key: 54-6ESzAXa7E7ZqCykrZ6IzmyqolcRRrneYr7cuNTyY
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: cnf.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: HKT-CNF
  port: 4447
  reality-opts:
    public-key: 54-6ESzAXa7E7ZqCykrZ6IzmyqolcRRrneYr7cuNTyY
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: cnf.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: TW-CNF
  port: 4448
  reality-opts:
    public-key: 54-6ESzAXa7E7ZqCykrZ6IzmyqolcRRrneYr7cuNTyY
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: cnf.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: VN-CNF
  port: 4449
  reality-opts:
    public-key: 54-6ESzAXa7E7ZqCykrZ6IzmyqolcRRrneYr7cuNTyY
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: cnf.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: JP-CNF
  port: 4500
  reality-opts:
    public-key: 54-6ESzAXa7E7ZqCykrZ6IzmyqolcRRrneYr7cuNTyY
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: cnf.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: DE-CNF
  port: 4501
  reality-opts:
    public-key: 54-6ESzAXa7E7ZqCykrZ6IzmyqolcRRrneYr7cuNTyY
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: cnf.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
- alpn:
  - h2
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: VLESS-CNF
  port: 4443
  reality-opts:
    public-key: 54-6ESzAXa7E7ZqCykrZ6IzmyqolcRRrneYr7cuNTyY
    server-name: hkust.edu.hk
    short-id: 9527abcd
  server: cnf.julao.de
  tls: true
  type: vless
  udp: true
  uuid: 297b8b7e-a886-4431-a6a9-25056ed46e76
proxy-groups:
- interval: 300
  name: Auto
  proxies: &id001
  - CNF-ALICE
  - Alice
  - SG-CNF
  - HKT-CNF
  - TW-CNF
  - VN-CNF
  - JP-CNF
  - DE-CNF
  - VLESS-CNF
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: Manual
  proxies: *id001
  type: select
rules:
- MATCH,Auto
socks-port: 7891
